version: '3.9'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "bookkeeper"
      POSTGRES_USER: "pg"
      POSTGRES_PASSWORD: "1234567"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data
